#!/usr/bin/env bash

bluetoothctl power on
if bluetoothctl info 88:D0:39:6B:77:2B | grep 'Connected: yes'
then
  mocp -P
  bluetoothctl disconnect 88:D0:39:6B:77:2B
else
  bluetoothctl connect 88:D0:39:6B:77:2B
fi
