#!/usr/bin/env bash

bluetoothctl power on
if bluetoothctl info E8:D0:3C:97:58:13 | grep 'Connected: yes'
then
  mocp -P
  bluetoothctl disconnect E8:D0:3C:97:58:13
else
  bluetoothctl connect E8:D0:3C:97:58:13
fi
