#!/usr/bin/env bash

currdir=$(pwd)
mv "$currdir/$1" ~/.dotfiles/
ln -s ~/.dotfiles/$1 "$currdir/"
link="ln -s ~/.dotfiles/${1%/} "$(echo $currdir/ | sed "s:$HOME:~:")
echo $link
echo $link >> ~/.dotfiles/linkall
