#!/usr/bin/env bash
mkdir -p ~/.local/bin
ln -s ~/.scripts/0x0 ~/.local/bin/
ln -s ~/.scripts/dotmv ~/.local/bin/
ln -s ~/.scripts/ext ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-bluetooth-switch ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-daily ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-menu ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-mocp ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-movies ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-mpris ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-search ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-todo ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-mount ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-umount ~/.local/bin/
ln -s ~/.scripts/send ~/.local/bin/
ln -s ~/.scripts/vimv ~/.local/bin/
ln -s ~/.scripts/screenshot ~/.local/bin/
ln -s ~/.scripts/prompt ~/.local/bin/
ln -s ~/.scripts/samedir ~/.local/bin/
ln -s ~/.scripts/ani-rofi ~/.local/bin/
