#!/usr/bin/env bash
mkdir -p ~/.local/bin
ln -s ~/.scripts/0x0 ~/.local/bin/
ln -s ~/.scripts/dotmv ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-menu ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-mpris ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-mount ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-umount ~/.local/bin/
ln -s ~/.scripts/rofi/rofi-spotify ~/.local/bin/
ln -s ~/.scripts/screenshot ~/.local/bin/
ln -s ~/.scripts/prompt ~/.local/bin/
ln -s ~/.scripts/search ~/.local/bin
ln -s ~/.scripts/screenshare ~/.local/bin
ln -s ~/.scripts/nyaa·si ~/.local/bin
ln -s ~/.scripts/1337x-torrent ~/.local/bin
