#!/usr/bin/env python3

from threading import Thread
from pynput import mouse
import time
import struct
import uinput
import keyboard
import mouse as mouse2

stop_mouse = False
mice = open("/dev/input/mouse1", "rb")

events = (
    uinput.ABS_X + (-100, 100, 0, 0), uinput.ABS_Y + (-100, 100, 0, 0),
    uinput.ABS_RX + (-1000, 1000, 0, 0), uinput.ABS_RY + (-1000, 1000, 0, 0),
    uinput.BTN_TL, uinput.BTN_TR, uinput.BTN_START, uinput.BTN_SELECT,
    uinput.BTN_TL2, uinput.BTN_TR2, uinput.BTN_DPAD_DOWN, uinput.BTN_DPAD_LEFT,
    uinput.BTN_DPAD_RIGHT, uinput.BTN_DPAD_UP, uinput.BTN_THUMBL,
    uinput.BTN_THUMBR, uinput.BTN_B, uinput.BTN_A, uinput.BTN_X, uinput.BTN_Y
        )
device = uinput.Device(events)
keyboardd = uinput.Device((uinput.KEY_R, uinput.KEY_LEFTALT))


def key_press(key):  # toggle mouse movement
    global stop_mouse
    if key.name == "|":
        stop_mouse = not stop_mouse


keyboard.on_press(key_press)


def get_mouse_event():
    global x
    global y
    speed = 200
    pX = 0
    pY = 0
    x = 0
    y = 0

    while True:
        if stop_mouse:
            buf = mice.read(3)
            x, y = struct.unpack("bb", buf[1:])

            X = int((x*speed+pX)/2)
            Y = int((y*speed+pY)/2)
            device.emit(uinput.ABS_RX, X)
            device.emit(uinput.ABS_RY, -Y)
            pX = X
            pY = Y
            print(X, Y)


def mouse_move():
    i = 0
    global x
    global y
    pX = 0
    pY = 0
    while True:
        time.sleep(0.01)
        if x == pX and y == pY:
            i += 1
            if i > 2:
                device.emit(uinput.ABS_RX, 0)
                device.emit(uinput.ABS_RY, 0)
        else:
            i = 0
        pX = x
        pY = y


def mouse_no_move():
    global stop_mouse
    while True:
        if stop_mouse:
            mouse2.move(10000, 10000)


def on_click(x, y, button, pressed):
    if button == mouse.Button.right and pressed and stop_mouse:
        device.emit(uinput.BTN_TR2, 1)
    else:
        device.emit(uinput.BTN_TR2, 0)

    if button == mouse.Button.left and pressed and stop_mouse:
        device.emit(uinput.BTN_X, 1)
    if not pressed:
        device.emit(uinput.BTN_X, 0)

    if button == mouse.Button.middle and pressed and stop_mouse:
        device.emit(uinput.BTN_THUMBR, 1)
    if not pressed:
        device.emit(uinput.BTN_THUMBR, 0)


def on_scroll(x, y, dx, dy):
    pass


def on_move(x, y):
    pass


listener = mouse.Listener(
    on_move=on_move,
    on_click=on_click,
    on_scroll=on_scroll)
listener.start()


Thread(target=get_mouse_event).start()
Thread(target=mouse_move).start()
Thread(target=mouse_no_move).start()
