#!/usr/bin/env bash

usage_root=$(lsblk -o mountpoint,fsuse% | grep "/ ")
usage_root=${usage_root#"/             "}
usage_mnt=$(lsblk -o mountpoint,fsuse% | grep "/mnt/mnt")
usage_mnt=${usage_mnt#"/mnt/mnt      "}

if lsblk -o mountpoint | grep -q "/mnt/mnt"; then
	echo "/ $usage_root, /m/mnt $usage_mnt"
else
	echo "/ $usage_root"
fi
