#!/usr/bin/env bash

if bluetoothctl show | grep -q "Powered: yes"; then
  if bluetoothctl info E8:D0:3C:97:58:13 | grep -q "Connected: yes"; then
		if bluetoothctl info 22:22:FF:4F:97:5D | grep -q "Connected: yes"; then
      echo " "
    else
			echo ""
    fi
  elif bluetoothctl info 22:22:FF:4F:97:5D | grep -q "Connected: yes"; then
    echo ""
  else
		echo ""
  fi
else
	echo ""
fi
