#!/usr/bin/env python3

import subprocess

usage_sda = subprocess.getoutput("lsblk -o name,fsuse% | grep nvme0n1p2").replace("└─nvme0n1p2    ", "")
usage = subprocess.getoutput("lsblk -o label,fsuse% | grep 'New Disk'").replace("New Disk    ", "")
usage2 = subprocess.getoutput("lsblk -o name,fsuse% | grep nvme0n1p3").replace("└─nvme0n1p3    ", "")
disk_labels = subprocess.getoutput("lsblk -o label")
if not "New Disk" in disk_labels:
    print("/m/files " + usage2)
else:
    print("/m/files " + usage2 + ", /m/mnt: " + usage)
