#!/bin/sh

function status {
	case "$(playerctl -l 2> /dev/null | grep spotify)" in
		spotify)
			artist=$(playerctl metadata --player=spotify artist)
			title=$(playerctl metadata --player=spotify title)
			icon=''
			artist="%{A3:playerctl previous --player=spotify:}$artist%{A}"
			title="%{A3:playerctl next --player=spotify:}$title%{A}"
			
			if [ "$(playerctl status --player=spotify)" = "Playing" ]; then
				icon="%{F#1db954}$icon%{F-}"
			else
				icon="%{F#808080}$icon%{F-}"
			fi
			text="$icon $artist - $title"

			# left click - play/pause
			text="%{A1:playerctl -p spotify play-pause:}$text%{A}"
			# middle click - go forward
			text="%{A2:playerctl -p spotify next; playerctl -p spotify previous :}$text%{A}"

			echo "$text"
			;;
		*)
			echo ""
			;;
	esac
}

status
