#!/bin/sh

search=$(echo "?" | rofi -dmenu -p "Search")
# exit if search is empty
if [ -z "$search" ]; then
    exit
fi
if [[ $search == "?" ]]; then
	search=$(cat -E ~/.cache/search-hist | tac | xargs echo " last++\$" | tr \$ "\n" | rofi -dmenu -p "Search")
fi
if [ -z "$search" ]; then
    exit
fi

UpANumber()
{
  local prefix number
  if [[ $@ =~ ^(.*[^[:digit:]])([[:digit:]]+)$ ]]; then
    prefix=${BASH_REMATCH[1]}
    number=${BASH_REMATCH[2]}
    printf '%s%s\n' "$prefix" "$(( number + 1 ))"
  else
    printf '%s\n' "$1"
  fi
}


if [[ $search == " last++" ]]; then
	search=$(UpANumber $(tail ~/.cache/search-hist -n1))
fi

# check if the search matches a whole line from history file
grep -x "$search" ~/.cache/search-hist > /dev/null
if [ $? -eq 0 ]; then
    # if it does, remove the line from history file
    sed -i "/$search/d" ~/.cache/search-hist
fi
# add the search to the top of history file
echo "$search" >> ~/.cache/search-hist

# get the all the words except the first one
words=$(echo $search | cut -d " " -f 2-)
# get the first word
first_word=$(echo $search | cut -d " " -f 1)
echo $first_word

case "$first_word" in
	"1")
		# search the 1337x
		firefox "https://1337x.to/search/$words/1/"
		;;
	"rl")
		# search the rutracker with linux games category
		firefox "https://rutracker.org/forum/tracker.php?nm=$words&f=1992,2059"
		;;
	"r")
		# search the rutracker
		firefox "https://rutracker.org/forum/tracker.php?nm=$words"
		;;
	"a")
		# search the archwiki
		firefox "https://wiki.archlinux.org/index.php?search=$words"
 		;;
	"h")
		# input href
		firefox "$words"
		;;
	"o")
		# search osu beatmaps
		firefox "https://osu.ppy.sh/beatmapsets?m=0&q=$words"
		;;
	"y")
		# search youtube
		firefox "https://www.youtube.com/results?search_query=$words"
		;;
	"w")
		# wolfram alpha
		firefox "https://www.wolframalpha.com/input/?i=$words"
		;;
	"t")
		# search and download torrent
		1337x-torrent "$words"
		;;
	"n")
		~/.scripts/nyaa·si "$words"
		;;
	"") exit ;;
	*)
		# search via duckduckgo
		firefox "https://duckduckgo.com/$words"
		;;
esac
