#!/bin/sh

add_todo() {
	if [ $# -eq 1 ]; then
		read -p "todo: " todo
	else
		todo=${@#"-a"}
	fi
	echo $todo >> ~/.cache/todos
}

del_todo() {
	if [ $# -eq 0 ]; then
		i=0
		while read line; do
			i=$((i+1))
			echo "$i: $line"
		done < ~/.cache/todos
		read -p "todo to delete: " num
	else
		num=$1
	fi
	sed -i "$num d" ~/.cache/todos
}

show() {
	while true; do
		i=0
		[ -s ~/.cache/todos ] || echo ""
		while read line; do
			i=$((i+1))
			echo "$i: $line"
			sleep $1
		done < ~/.cache/todos
	done
}

case $1 in
	-a) add_todo $@;;
	-d) del_todo $2;;
	-s) show $2;;
esac
