#!/usr/bin/env bash

if ! bluetoothctl show | grep -q "Powered: yes"; then
	bluetoothctl power on
	bluetoothctl connect 88:D0:39:6B:77:2B
	if bluetoothctl info | grep -q "Connected: yes"; then
		exit
	fi
fi

profile=$(pactl list cards | grep bluez_card.88_D0_39_6B_77_2B --after-context 27 | grep 'Active Profile')
profile=${profile#"	Active Profile: "}
profile=${profile%"-aac"}
profile=${profile%"-msbc"}

battery=$(upower --dump | grep "JBL TUNE660NC" --after-context 8 | grep percentage)
battery=${battery#"    percentage:          "}
battery="$battery%"

case "$(printf "quick connect/disconnect\n$profile\n$battery\nbluetooth manager" | rofi -dmenu -l 3 -i -p "bluetooth menu" -width 20)" in
	"quick connect/disconnect") if bluetoothctl info 88:D0:39:6B:77:2B | grep -q "Connected: no"; then
		bluetoothctl connect 88:D0:39:6B:77:2B
	else
		bluetoothctl disconnect 88:D0:39:6B:77:2B
		fi ;;
	"battery level") battery_level=$(bluetooth-headset-battery-level 88:D0:39:6B:77:2B.1)
		rofi -dmenu -p "${battery_level#"Battery level for 88:D0:39:6B:77:2B is "}" -l 0 -width 5 ;;
	"a2dp-sink") pactl set-card-profile bluez_card.88_D0_39_6B_77_2B headset-head-unit ;;
	"headset-head-unit") pactl set-card-profile bluez_card.88_D0_39_6B_77_2B a2dp-sink ;;
	"bluetooth manager") rofi-bluetooth ;;
esac
