#!/usr/bin/env bash

if ! bluetoothctl show | grep -q "Powered: yes"; then
	bluetoothctl power on
	bluetoothctl connect 88:D0:39:6B:77:2B
	if bluetoothctl info | grep -q "Connected: yes"; then
		exit
	fi
fi

profile=$(pactl list cards | grep bluez_card.88_D0_39_6B_77_2B --after-context 28 | grep 'Active Profile')
profile=${profile#"	Active Profile: "}
profile=${profile%"-aac"}
profile=${profile%"-msbc"}

battery=$(upower --dump | grep "JBL TUNE660NC" --after-context 8 | grep percentage)
battery=${battery#"    percentage:          "}
battery="$battery%"
connection_status="disconnected"

if bluetoothctl info | grep -q "Connected: yes" && bluetoothctl info | grep -q "JBL"; then
	connection_status="connected"
fi

case "$(printf "quick connect/disconnect ($connection_status)\nbluetooth manager\n$profile\n$battery" | rofi -dmenu -l 4 -i -p "bluetooth menu" -width 20)" in
	"quick connect/disconnect (connected)") bluetoothctl disconnect 88:D0:39:6B:77:2B ;;
	"quick connect/disconnect (disconnected)") bluetoothctl connect 88:D0:39:6B:77:2B ;;
	"a2dp-sink") pactl set-card-profile bluez_card.88_D0_39_6B_77_2B headset-head-unit ;;
	"headset-head-unit") pactl set-card-profile bluez_card.88_D0_39_6B_77_2B a2dp-sink ;;
	"bluetooth manager") rofi-bluetooth ;;
esac
