#!/usr/bin/env python3

import os
from rofi import Rofi

r = Rofi()
path = "/mnt/mnt/Michal/Downloads/Movies"
if not os.path.isfile(path):
    path = "/home/michal"

mv = False

while True:
    for (dirpath, dirnames, filenames) in os.walk(path + "/"):

        rdirs = [".."]
        rdirnames = []
        for i,dirname in enumerate(dirnames):
            rdirnames.append("/"+dirname)
        rdirs.extend(rdirnames)
        rdirs.extend(filenames)

        dirs = [".."]
        dirs.extend(dirnames)
        dirs.extend(filenames)


        for i in range(len(dirs)): # for some reason -i doesnt work, so I did this instead
            rdirs[i] = rdirs[i].lower()
        if mv == True: # highlight selected files
            for i,dirname in enumerate(dirs):
                for j,mfile in enumerate(mfiles):
                    if mfile == dirname:
                        rdirs[i] = "* " + rdirs[i]

        index, key = r.select(
                "Watch",
                rdirs,
                key1=("Alt+v", "open folder in VLC"), 
                key2=("Alt+x", "move"), 
                key3=("Alt+d", "delete"), 
                )

        if key == 0:
            if mv == True:
                if dirs[index] in mfiles:
                    r.error("you cannot move a file into a file selected for moving")
                elif index == 0: # move files back a dir
                    splitPath = path.split("/")
                    del splitPath[-1]
                    mvPath = ""
                    for val in splitPath:
                        if val != "":
                           mvPath += "/" + val
                    for mfile in mfiles:
                        os.system("mv "+dirpath+mfile+" "+mvPath+"/")
                else:
                    for mfile in mfiles:
                        os.system("mv "+dirpath+mfile+" "+dirpath+dirs[index]) # move files
                mv = False
            elif index == 0: # go back a dir
                splitPath = path.split("/")
                del splitPath[-1]
                path = ""
                for val in splitPath:
                    if val != "":
                        path += "/" + val
                
            elif index <= len(dirnames):
                path += "/" + dirnames[index-1] # change dir
            elif ".mkv" in filenames[index-len(dirnames)-1] or ".mp3" in filenames[index-len(dirnames)-1]: # check if file is a movie, and if so open it in vlc
                os.system("vlc '{}/{}'".format(path, filenames[index-len(dirnames)-1]))
                exit()
        elif key == 1: # open dir in VLC
            os.system("vlc '{}'".format(path + "/" + dirnames[index-1]))
            exit()
        elif key == 2:
            if mv == False:
                mv = True
                mfiles = []
                mfiles.append(dirs[index]) # set file for moving
            else:
                mfiles.append(dirs[index]) # append file for moving

        elif key == 3: # delete a file
            i, k = r.select("are u sure u want to delete "+dirs[index]+" ?", ["no","yes"])
            if k == 0 and i == 1:
                os.system("rm -rf "+dirpath+dirs[index])
        else:
            exit()
        break
