#!/usr/bin/env python3

import os
from rofi import Rofi

r = Rofi()
#  menus = ["-p | piratebays", "-a | archwiki.com"]

input = r.text_entry(
        "Search",
        #  message="<span foreground='#d0d0d0'>-p  piratebays\n-a  archwiki</span>",
        lines=1,)

if input[0 : 2] == "p ":
    os.system("firefox 'thepiratebay10.org/search/{}'".format(input[2 : ]))
if input[0 : 2] == "a ":
    os.system("firefox 'wiki.archlinux.org/index.php?search={}'".format(input[2 : ]))
if input[0 : 2] == "h ":
    os.system("firefox '{}'".format(input[2 : ]))
if input[0 : 2] == "r/":
    os.system("firefox reddit.com/"+input)
elif input:
    os.system("firefox 'www.duckduckgo.com/{}'".format(input))
