#!/usr/bin/env bash

adb connect 192.168.1.111

path="/sdcard"
selection="0"

while (true) ; do
	if [ $prev = $selection ] ; then
		exit
	fi
	prev="$selection/"
	selection="$path/$(adb shell ls -1 $path | rofi -dmenu)"

	if $(adb shell [ -d $selection ]) ; then
		path=$selection
	elif $(adb shell [ -f $selection ]) ; then
		adb pull $selection
		exit
	fi
done
