#!/usr/bin/env python3

import argparse
import json
from json import JSONDecodeError

from rofi import Rofi

parser = argparse.ArgumentParser()
parser.add_argument(
    "-f", "--file", help="specify path to notes notes file", required=True
)
parser.add_argument(
    "-a", "--afile", help="specify path to notes archive file", required=True
)
parser.add_argument(
    "--init", help="clear and initialize notes file", action="store_true"
)
args = parser.parse_args()

titles = []
r = Rofi()


def init_file():
    inote = {"notes": [{"name": "empty", "description": "empty"}]}
    with open(args.file, "w") as f:
        json.dump(inote, f, indent=2)
    with open(args.afile, "w") as f:
        json.dump(inote, f, indent=2)
    print("Files are reset and initialized again.")
    r.error("FIles are reset and initialized again.")
    exit()


if args.init:
    init_file()


try:
    with open(args.file) as f:
        notes = json.load(f)
    with open(args.afile) as f:
        archive = json.load(f)

except JSONDecodeError:
    print("JSONDecodeError")
    init_file()
except KeyError:
    print("KeyError")
    init_file()


def show_titles():
    for i in range(len(notes["notes"])):
        titles.append(notes["notes"][i]["name"])


try:
    while True:
        titles = []
        show_titles()

        index, key = r.select(
            "todo",
            titles,
            key1=("Alt+d", "delete a todo"),
            key2=("Alt+a", "add a todo"),
            rofi_args=["-i", "-no-custom", "-l", "15"],
        )

        if key == 0:
            r.error(notes["notes"][index]["description"])

        elif key == 1:
            archive["notes"].append(notes["notes"][index])
            with open(args.afile, "w") as f:
                json.dump(archive, f, indent=2)

            del notes["notes"][index]

            with open(args.file, "w") as f:
                json.dump(notes, f, indent=2)

                r.error("Note deleted.")

        elif key == 2:
            name = r.text_entry("Enter note name", rofi_args=["-l", "0"])

            if name:
                desc = r.text_entry("Enter node description", rofi_args=["-l", "0"])
                new_note = {"name": name, "description": desc}
                notes["notes"].append(new_note)

                with open(args.file, "w") as f:
                    json.dump(notes, f, indent=2)

                    r.error("Note added.")

        else:
            break

except IndexError:
    print("IndexError")
    init_file()
except KeyError:
    print("KeyError")
    init_file()
