#!/usr/bin/env bash

menus="墳 change sink\n kdeconnect menu\n restart bspwm\n bluetooth menu\n爵 search\n  0x0.st\n clipboard\n calculator\n aplication menu\n launch mocp\n kill music\n scrcpy\n scrcpy over network\n adb over network\n todo\n kill session\n鈴 sleep\n  minecraft wither skeleton farm\n  minecraft creeper farm"

case "$(echo -en $menus | rofi -dmenu -p "rofi-menu")" in
	"墳 change sink") pulseaudio-control next-sink ;;
	" kdeconnect menu") ~/.scripts/polybar-kdeconnect.sh -c -g -n 'Redmi' -i 954ba9f16268dab7 -m ;;
	" restart bspwm") ~/.scripts/killall.sh ;;
	" bluetooth menu") rofi-bluetooth-switch ;;
	"爵 search") rofi-search ;;
	" 0x0.st") 0x0 ;;
	" clipboard") rofi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}' ;;
	" calculator") rofi -show calc -modi calc -no-show-match -no-sort ;;
	" aplication menu") rofi drun -show drun -show-icons ;;
	" launch mocp") mocp -S ;;
	" kill music") killall mocp ;;
	" scrcpy") scrcpy ;;
	" scrcpy over network") scrcpy -m 720 -b 800000 ;;
	" adb over network") adb connect 192.168.1.111 ;;
	" todo") rofi-todo -f ~/Documents/todo.json -a ~/Documents/todoarchive.json ;;
	" kill session") killall Xorg ;;
	"鈴 sleep") systemctl suspend ;;
	" minecraft wither skeleton farm") xclip -selection c ~/Documents/witherFarm ;;
	" minecraft creeper farm") xclip -selection c ~/Documents/creeperFarm ;;
esac
