#!/usr/bin/env python3

import os
from rofi import Rofi

r = Rofi()
#  menus = ["-p | piratebays", "-a | archwiki.com"]

search = r.text_entry(
        "Search",
        #  message="<span foreground='#d0d0d0'>-p  piratebays\n-a  archwiki</span>",
        lines=1,)

if search[0:2] == "p ":
    os.system('''firefox "thepiratebay10.org/search/{}"'''.format(search[2 : ]))
elif search[0:2] == "1 ":
    os.system('''firefox "1337x.to/search/{}/1"'''.format(search[2 : ]))
elif search[0:3] == "rl ":
    os.system('''firefox "https://rutracker.org/forum/tracker.php?f=1992,2059&nm={}"'''.format(search[3 : ]))
elif search[0:2] == "r ":
    os.system('''firefox "https://rutracker.org/forum/tracker.php?nm={}"'''.format(search[2 : ]))
elif search[0:2] == "a ":
    os.system('''firefox "wiki.archlinux.org/index.php?search={}"'''.format(search[2 : ]))
elif search[0:2] == "h ":
    os.system('''firefox "{}"'''.format(search[2 : ]))
elif search[0:2] == "r/":
    os.system('''firefox reddit.com/'''+search)
elif search[0:2] == "o ":
    os.system('''firefox "https://osu.ppy.sh/beatmapsets?m=0&q={}"'''.format(search[2:]))
elif search[0:2] == "y ":
    os.system('''firefox "https://www.youtube.com/results?search_query={}"'''.format(search[2:]))
elif search[0:2] == "w ":
    os.system('''firefox "https://www.wolframalpha.com/input/?i={}"'''.format(search[2:]))
elif search == "t":
    os.system('''1337x-torrent''')
else:
    os.system('''firefox "www.duckduckgo.com/{}"'''.format(search))
