#!/usr/bin/env python3

import os
from rofi import Rofi

r = Rofi()
menus = [
        "墳 change sink",
        " kdeconnect menu",
        " restart bspwm",
        " bluetooth menu",
        "爵 search",
        "  0x0.st",
        " clipboard",
        " calculator",
        " aplication menu",
        " launch mocp",
        " kill music",
        " scrcpy",
        " scrcpy over network",
        " adb over network",
        " todo",
        " kill session",
        "鈴 sleep",
        "  minecraft wither skeleton farm",
        "  minecraft creeper farm",
        ]
programs = [
        "pulseaudio-control next-sink",
        "~/.scripts/polybar-kdeconnect.sh -c -g -n 'Redmi' -i 954ba9f16268dab7 -m",
        "~/.scripts/killall.sh",
        "rofi-bluetooth-switch",
        "rofi-search",
        "0x0",
        "rofi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}'",
        "rofi -show calc -modi calc -no-show-match -no-sort",
        "rofi drun -show drun -show-icons",
        "mocp -S",
        "killall mocp",
        "scrcpy",
        "scrcpy -m 720 -b 800000",
        "adb connect 192.168.1.111",
        "rofi-todo -f ~/Documents/todo.json -a ~/Documents/todoarchive.json",
        "killall Xorg",
        "systemctl suspend",
        "xclip -selection c ~/Documents/witherFarm",
        "xclip -selection c ~/Documents/creeperFarm",
        ]

while True:
    index, key = r.select("Menu",menus)
    if key == 0:
        os.system(programs[index])
    break

