#!/usr/bin/env python3

import os
from rofi import Rofi

r = Rofi()
menus = [
        "墳 change sink",
        " kdeconnect menu",
        " kdeconnect connect",
        " redshift",
        " restart bspwm",
        " bluetooth menu",
        "爵 search",
        " clipboard",
        " calculator",
        " aplication menu",
        " launch mocp",
        " load music",
        " kill music",
        "裸 clean playlist",
        " scrcpy",
        " scrcpy over network",
        " adb over network",
        " external monitor on",
        " external monitor off",
        " todo",
        " homework",
        " kill session",
        "鈴 sleep",
        ]
programs = [
        "pulseaudio-control next-sink",
        "~/.scripts/polybar-kdeconnect.sh -c -g -n 'Redmi' -i 954ba9f16268dab7 -m",
        "kdeconnect-cli --pair -n Redmi",
        "redshift -l 53.571709:20.977576",
        "~/.scripts/killall.sh",
        "rofi-bluetooth-switch",
        "rofi-search",
        '''rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' -font "Inconsolata 14"''',
        "rofi -show calc -modi calc -no-show-match -no-sort",
        '''rofi drun -show drun -show-icons -font "Inconsolata 14''',
        "mocp -S",
        "mocp -o shuffle -p -a ~/.music/",
        "killall mocp",
        "mocp -c",
        "scrcpy",
        "scrcpy -m 720 -b 800000",
        "adb connect 192.168.1.111:5555",
        "xrandr --output DP1-3 --mode 1280x1024 --rate 75.00 --right-of eDP1; bspc monitor eDP1 -d I II III IV V VI; bspc monitor DP1-3 -d VII VIII IX",
        "xrandr --output DP1-3 --off",
        "rofi-todo -f ~/Documents/todo.json -a ~/Documents/todoarchive.json",
        "rofi-todo -f ~/Documents/homework.json -a ~/Documents/homework_done.json",
        "killall Xorg",
        "sudo pm-suspend",
        ]

while True:
    index, key = r.select("Menu",menus)
    if key == 0:
        os.system(programs[index])
    break

